#!/bin/sh

CONFIGFILE=/etc/mplayer-stereoscopic/mplayer-stereoscopic.conf

set -e

# Source debconf library.
. /usr/share/debconf/confmodule

if test -r $CONFIGFILE && ! grep -q '### mplayer-stereoscopic DEBCONF AREA' $CONFIGFILE
then
    db_input medium 'mplayer-stereoscopic/replace-existing-files'  || true
    db_go || true
    if [ "$RET" != "true" ]; then
        exit 0
    fi
    db_get  'mplayer-stereoscopic/replace-existing-files' || true
fi

########################################## find fonts
#default font (if available)
BESTFONT=/usr/share/fonts/truetype/Arial.ttf
[ -r $BESTFONT ] || BESTFONT=/usr/share/fonts/truetype/freefont/FreeSans.ttf

t=$(tempfile -p fonts )
find /usr/share/fonts/ /?/?in*/?ont* -type f -iname '*.ttf' -maxdepth 3 2> /dev/null  > $t  || true

if test -s $t
then
    fonts=$( awk '{print a $0;a=", "}' $t || true )
    db_subst "mplayer-stereoscopic/ttfont" ttfontchoices $fonts  || true
 ## suppose the question is skipped: give a default
    a=$BESTFONT
    [ -r $BESTFONT ] || a=$(head -1 $t)
    db_subst "mplayer-stereoscopic/ttfont" ttfontdefault $a  || true

    db_input medium  mplayer-stereoscopic/ttfont  || true
    if [ "$?" = 30 ] ; then
        db_set  mplayer-stereoscopic/ttfont $a  || true
    fi
else
    db_input medium "mplayer-stereoscopic/no-ttfont" || true
fi

rm $t

db_go || true

############################################################


exit 0
